### ISSUE TITLE
ROAR Sim and ROAR Jetson not fully seperated

### ISSUE THREAD

**Issue by wuxiaohua1011** [augcog/ROAR_Sim#19]
**Describe the bug**
When running on Jetson Nano, Carla.egg is not a thing, therefore error out

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "runner_jetson.py", line 4, in <module>
    from ROAR.roar_autonomous_system.configurations.configuration import Configuration
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/roar_autonomous_system/configurations/configuration.py", line 3, in <module>
    from ROAR.carla_client.carla_settings import CarlaConfig
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/carla_client/carla_settings.py", line 20, in <module>
    from ROAR.carla_client.util.utilities import CarlaWeathers, \
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/carla_client/util/utilities.py", line 2, in <module>
    import carla
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/carla_client/carla-0.9.9-py3.6-linux-x86_64.egg/carla/__init__.py", line 8, in <module>
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/carla_client/carla-0.9.9-py3.6-linux-x86_64.egg/carla/libcarla.py", line 7, in <module>
  File "/home/michael/Desktop/projects/ROAR-Sim/ROAR/carla_client/carla-0.9.9-py3.6-linux-x86_64.egg/carla/libcarla.py", line 6, in __bootstrap__
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/michael/.cache/Python-Eggs/carla-0.9.9-py3.6-linux-x86_64.egg-tmp/carla/libcarla.cpython-36m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. `git clone --recursive ROAR-Sim`
2. `python3 runner_jetson.py`

**Expected behavior**
It should just run

**Desktop (please complete the following information):**
 - OS: ROAR Jetson Jetpack 4.4

**Comment by wuxiaohua1011** [comment]
solved in michael branch
